version: '3'

services:
  db:
    image: postgres:9.6.11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python3 manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data: