version: '3'

services:
  db:
    image: postgres:9.6.11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:alpine
  web:
    build: .
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: python3 manage.py runserver 0.0.0.0:8000
  celery:
    build: .
    command: celery -A demo worker -l info
    volumes:
      - .:/code/
    depends_on:
      - db
      - redis
volumes:
  postgres_data: